table 'Bench (2)'
	lineageTag: bf242a94-860f-4f55-9015-ebe814ced39c

	column 'Fecha de carga'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b8b0ea7e-495a-49df-b2d3-2f0a913c4bec
		summarizeBy: none
		sourceColumn: Fecha de carga

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Campaña
		dataType: string
		lineageTag: 38739195-01d2-4bcb-a07b-c2d0395062a9
		summarizeBy: none
		sourceColumn: Campaña

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: f9fe323b-7209-4b47-9196-8553101d8251
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column '% Recorrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1288e3e3-d059-4d5d-80b3-a8f4cd31c0d8
		summarizeBy: sum
		sourceColumn: % Recorrido

		annotation SummarizationSetBy = Automatic

	column '% Contactabilidad'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7bfa4a44-5de7-4f59-a0aa-fbb1b0979f1c
		summarizeBy: sum
		sourceColumn: % Contactabilidad

		annotation SummarizationSetBy = Automatic

	column 'Efec. Bruta'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 524b68fa-6287-4193-9bd4-0e270a5d0313
		summarizeBy: sum
		sourceColumn: Efec. Bruta

		annotation SummarizationSetBy = Automatic

	column 'Efect Neta'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 9e968298-6c2e-4567-8a75-eef053fc8506
		summarizeBy: sum
		sourceColumn: Efect Neta

		annotation SummarizationSetBy = Automatic

	column Vueltas
		dataType: string
		lineageTag: c00da162-cb7e-48ba-b7bc-2a604b84e551
		summarizeBy: none
		sourceColumn: Vueltas

		annotation SummarizationSetBy = Automatic

	column 'Mes bench'
		dataType: string
		lineageTag: c73271ad-c4b0-4585-a76a-a95a82fae4e2
		summarizeBy: none
		sourceColumn: Mes bench

		annotation SummarizationSetBy = Automatic

	column 'Año bench'
		dataType: string
		lineageTag: 24cf294e-4b60-4ad7-8e8e-fba5ca292dfb
		summarizeBy: none
		sourceColumn: Año bench

		annotation SummarizationSetBy = Automatic

	column 'Dia bench'
		dataType: string
		lineageTag: 865fd26d-2e86-4782-bd5a-7afefa95c61b
		summarizeBy: none
		sourceColumn: Dia bench

		annotation SummarizationSetBy = Automatic

	column 'Llave bench' = 'Bench (2)'[Campaña]&'Bench (2)'[Canal]&'Bench (2)'[Dia bench]&'Bench (2)'[Mes bench]&'Bench (2)'[Año bench]
		lineageTag: c6443ef0-4d53-4567-b8ad-625fd15ff39f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Contar = LEN('Bench (2)'[Vueltas])
		formatString: 0
		lineageTag: f18083aa-f2c9-46a0-9937-cc20a126515c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Vueltas reales' = if(MID('Bench (2)'[Vueltas],2,1)=".",(LEFT('Bench (2)'[Vueltas],1)&","&MID('Bench (2)'[Vueltas],3,2))*1,if(MID('Bench (2)'[Vueltas],3,1)=".",(LEFT('Bench (2)'[Vueltas],2)&","&MID('Bench (2)'[Vueltas],4,2))*1,IF(AND(LEN('Bench (2)'[Vueltas])=1,'Bench (2)'[Contar]>0),'Bench (2)'[Vueltas]*1,if('Bench (2)'[Contar]<10,("0"&","&LEFT('Bench (2)'[Vueltas],2))*1,IF('Bench (2)'[Contar]=10,(LEFT('Bench (2)'[Vueltas],1)&","&MID('Bench (2)'[Vueltas],3,2))*1,IF('Bench (2)'[Contar]>10,(LEFT('Bench (2)'[Vueltas],2)&","&MID('Bench (2)'[Vueltas],4,2))*1,1))))))
		lineageTag: 840f56b6-84e3-4828-8a20-03aced92c877
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prioridad = LOOKUPVALUE(Prioridad[prioridad],Prioridad[Campaña],'Bench (2)'[Campaña])
		lineageTag: 05a83b15-417d-494a-94f7-a8bb32df3bee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'llave campaña' = 'Bench (2)'[Campaña]&'Bench (2)'[Canal]
		lineageTag: b58ba156-a331-4543-9fd1-fa31a5bb641c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Bench (2)' = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:\Users\alejo\OneDrive\Documentos\Conocimiento\Power BI\Power bi Bench\Data\Bench"),
				    #"Archivos ocultos filtrados1" = Table.SelectRows(Origen, each [Attributes]?[Hidden]? <> true),
				    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo (3)", each #"Transformar archivo (3)"([Content])),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo (3)"}),
				    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo (3)", Table.ColumnNames(#"Transformar archivo (3)"(#"Archivo de ejemplo (3)"))),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Columna de tabla expandida1", "Source.Name", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Source.Name.1", "Source.Name.2", "Source.Name.3", "Source.Name.4", "Source.Name.5", "Source.Name.6", "Source.Name.7"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"Source.Name.1", type date}, {"Source.Name.2", type text}, {"Source.Name.3", type text}, {"Source.Name.4", type text}, {"Source.Name.5", type text}, {"Source.Name.6", type text}, {"Source.Name.7", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Source.Name.2", "Source.Name.3", "Source.Name.4", "Source.Name.5", "Source.Name.6", "Source.Name.7"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"Source.Name.1", "Fecha de carga"}}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Columnas con nombre cambiado", "Dia bench", each Date.Day([Fecha de carga])),
				    #"Personalizada agregada" = Table.AddColumn(#"Personalizada agregada2", "Mes bench", each Date.Month ([Fecha de carga])),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "Año bench", each Date.Year([Fecha de carga])),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"Año bench", type text}, {"Mes bench", type text}, {"Dia bench", type text}, {"Vueltas", type text}, {"Efec. Bruta", Percentage.Type}, {"Efect Neta", Percentage.Type}}),
				    #"Errores reemplazados2" = Table.ReplaceErrorValues(#"Tipo cambiado1", {{"Efect Neta", 0}}),
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Errores reemplazados2", {{"Efec. Bruta", 0}}),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Errores reemplazados1", {{"Vueltas", 0}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Errores reemplazados",null,"0",Replacer.ReplaceValue,{"Vueltas"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","-","0",Replacer.ReplaceText,{"Vueltas"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Valor reemplazado1",{{"% Contactabilidad", Percentage.Type}, {"% Recorrido", Percentage.Type}}),
				    #"Errores reemplazados3" = Table.ReplaceErrorValues(#"Tipo cambiado2", {{"% Contactabilidad", 0}}),
				    #"Errores reemplazados4" = Table.ReplaceErrorValues(#"Errores reemplazados3", {{"% Recorrido", 0}})
				in
				    #"Errores reemplazados4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

